### ISSUE TITLE
serializer.extract is not a function - after upgrade to Ember 2.5

### ISSUE THREAD

**Issue by phlcastro** [abuiles/ember-attachable#35]
Hi

after upgrade my project to Ember 2.5, the following error appeared:

`TypeError: serializer.extract is not a function`

That's basically because the line test `get(serializer, 'isNewSerializerAPI')` does not work as expected anymore.
[https://github.com/abuiles/ember-attachable/blob/master/addon/lib/serializer-response.js#L75](url)

Then the execution jumps to `var serializerPayload = serializer.extract(store, modelClass, payload, id, requestType);`
[https://github.com/abuiles/ember-attachable/blob/master/addon/lib/serializer-response.js#L89](url)

Since `DS.Serializer` changed the method `extract` to `normalizeResponse`, that line throws the error.

I did a "quick and dirt" fix on my repo (as you can see here [https://github.com/phlcastro/ember-attachable/commit/9bf7564ba70299c0e78b01226b53dbaea4c9e3a5](url)).
But if you want I can do something better and send a PR.

Thanks again for your work!

Best regards

**Comment by esbanarango** [comment]
@phlcastro Sure! Could you send a PR and we can discuss about it. Btw, the link you share doesn't work.

Thank you.

**Comment by phlcastro** [comment]
@esbanarango fixed links.

should we keep ember-attachment compatible with Ember 1.x and 2.x?

**Comment by phlcastro** [comment]
@esbanarango I already have a PR opened with you abuiles/ember-attachable/pull/34

so, github is including the commit to fix this bug there too.

would you mind to review both and merge them? (or eventually tell me to fix something before merge)

TravisCI is throwing a timeout error, but I dont know why.
https://travis-ci.org/abuiles/ember-attachable/builds/133133277

thanks!

**Comment by esbanarango** [comment]
Thank you @phlcastro. I'll fix the Travis timeout error on master.
